### ISSUE TITLE
Sorry, this tree took too long to generate.

### ISSUE THREAD

**Issue by metaiiica** [PAC-ROM/android_vendor_pac#100]
when i go to PAC-man / android_vendor_pac, i have following Message only:

Sorry,
this tree took too long to generate.

How can i fix that?

**Comment by Nick0703** [comment]
I'm getting the same msg??

**Comment by Wechy77** [comment]
i'm getting the same
With phone and dolphin browser i can reach it without error. But with pc
and chrome gives me error

2013/4/12 Nick notifications@github.com

**Comment by singhdd93** [comment]
Same here

**Comment by Grarak** [comment]
Yep I have it too

**Comment by metaiiica** [comment]
Now we have a blind date. merge all was come xD

**Comment by metaiiica** [comment]
this is a joke^^

**Comment by Nick0703** [comment]
Try using this link https://github.com/PAC-man/android_vendor_pac/tree, it works for me.
