### ISSUE TITLE
Phone: Add Blacklist functionality

### ISSUE THREAD

**Issue by Wechy77** [PAC-ROM/android_vendor_pac#102]
packages/apps/Phone/src/com/android/phone/InCallScreen.java:3188: error: cannot find symbol
            case R.id.addBlacklistButton:
                     ^
  symbol:   variable addBlacklistButton
  location: class id
packages/apps/Phone/src/com/android/phone/InCallTouchUi.java:197: error: cannot find symbol
        mAddBlacklistButton = (ImageButton) mInCallControls.findViewById(R.id.addBlacklistButton);
                                                                             ^
  symbol:   variable addBlacklistButton
  location: class id
packages/apps/Phone/src/com/android/phone/InCallTouchUi.java:408: error: cannot find symbol
            case R.id.addBlacklistButton:
                     ^
  symbol:   variable addBlacklistButton
  location: class id

make: **\* [........../out/target/common/obj/APPS/Phone_intermediates/classes-full-debug.jar] Error 41
make: **\* Waiting for unfinished jobs....

and build stops

**Comment by TheRealChickenlegs** [comment]
Builds with no errors for me, did you try and sync again? 

Edit: Just checked the commit and the addBlacklistButton is definitely declared in the layout of the incall_touch.xml layout:
-                
-                <ImageButton android:id="@+id/addBlacklistButton" 

Screenshot is below of the blacklist screen:
http://i46.tinypic.com/348670n.png
Screenshot in call shows the blacklist button on the far right next to add contact:
http://i49.tinypic.com/29ll7rl.jpg

**Comment by Nick0703** [comment]
I've just compile a test and I didn't get any errors. It must be something on your end.

**Comment by Wechy77** [comment]
Solved
