### ISSUE TITLE
'make clean' and 'make clobber' broken

### ISSUE THREAD

**Issue by jeroenqui** [PAC-ROM/android_vendor_pac#104]
$ make clean
build/core/product_config.mk:237: **\* Product "full" ambiguous: matches build/target/product/full.mk vendor/pac/products/full.mk.  Stop.

$ make clobber
build/core/product_config.mk:237: **\* Product "full" ambiguous: matches build/target/product/full.mk vendor/pac/products/full.mk.  Stop.

**Comment by Nick0703** [comment]
Yeah, you're not the only one that's having this problem. It seems that this commit broke it https://github.com/PAC-man/android_vendor_pac/commit/7755af7024326e0f5bc799a9948d4cfc84a1e81a

**Comment by Nick0703** [comment]
Problem fixed.
