### ISSUE TITLE
Motorola Droid HD

### ISSUE THREAD

**Issue by Bkjolly** [PAC-ROM/android_vendor_pac#107]
I'm having an issue getting Hybrid Settings going on xt926 can someone please give me some insight. The Main Menu isn't showing at all and I am having to edit permissions on preferences.config after first boot.

**Comment by Papa-Smurf151** [comment]
please go to the pac man forum. register and send me a pm or msg here and
ill give u maintainer status so you can ask there.  we trouble shoot issues
there now

http://pac-man-rom.de/forum/index.php

**Comment by Bkjolly** [comment]
Thanks. Signed up and pm sent.
