### ISSUE TITLE
[bug] navbar rings 90° rotate in landscape

### ISSUE THREAD

**Issue by Suxsem** [PAC-ROM/android_vendor_pac#110]
in maguro_PAC_JB_4.2.2-v22.1.0_20130421-050149
i noticed a very infamous bug...
navbar rings rotate of 90° in landscape mode!
![Screenshot_2013-04-21-17-46-27](https://f.cloud.github.com/assets/830773/406527/dba6bc04-aa9c-11e2-8a4b-07f37b604db2.png)
![Screenshot_2013-04-21-17-45-48](https://f.cloud.github.com/assets/830773/406526/dba1f606-aa9c-11e2-98a0-1f0cea817cb6.png)

**Comment by Suxsem** [comment]
this happends only in phablet and tablet mode

**Comment by Grarak** [comment]
I already told him that isn't a bug
