### ISSUE TITLE
Build Error !!

### ISSUE THREAD

**Issue by blindndumb** [PAC-ROM/android_vendor_pac#123]
Notice file: external/zlib/NOTICE -- /home/blindndumb/ROM-Sources/PAC-man/out/target/product/saga/obj/NOTICE_FILES/src//system/lib/libz.a.txt
Notice file: external/libpng/NOTICE -- /home/blindndumb/ROM-Sources/PAC-man/out/target/product/saga/obj/NOTICE_FILES/src//system/lib/libpng.a.txt
Notice file: bionic/libstdc++/NOTICE -- /home/blindndumb/ROM-Sources/PAC-man/out/target/product/saga/obj/NOTICE_FILES/src//system/lib/libstdc++.a.txt
Notice file: external/libselinux/NOTICE -- /home/blindndumb/ROM-Sources/PAC-man/out/target/product/saga/obj/NOTICE_FILES/src//system/lib/libselinux.a.txt
Target buildinfo: /home/blindndumb/ROM-Sources/PAC-man/out/target/product/saga/system/build.prop
host Java: dumpkey (/home/blindndumb/ROM-Sources/PAC-man/out/host/common/obj/JAVA_LIBRARIES/dumpkey_intermediates/classes)

make: **\* No rule to make target `/home/blindndumb/ROM-Sources/PAC-man/out/host/linux-x86/obj/STATIC_LIBRARIES/libandroidfw_intermediates/export_includes', needed by`/home/blindndumb/ROM-Sources/PAC-man/out/host/linux-x86/obj/EXECUTABLES/aapt_intermediates/import_includes'.  Stop.
make: **\* Waiting for unfinished jobs....

Any Ideas ? Building after long time .. 
I guess this has something to do with it 
https://github.com/PAC-man/android_frameworks_base/commit/7afc16df39031e9726213356fbd5277ceac6c35c

**Comment by Papa-Smurf151** [comment]
Post this in forum please

**Comment by blindndumb** [comment]
Looks like saga(HTC Desire S) is completely thrown out of PAC , No idea where to post !!

**Comment by Papa-Smurf151** [comment]
If you are registered tell Me ur user name and I'll give u maintainer access

**Comment by blindndumb** [comment]
username : blindndumb

**Comment by Papa-Smurf151** [comment]
Ok your in as a Maintainer now.  You should see the maintainer forums now

**Comment by Bkjolly** [comment]
I'm having the same issue

**Comment by blindndumb** [comment]
If the issue is with the above mentioned commit then every one should have this error while building..
Anyone successfully built ??
No idea how to fix this :(

**Comment by gs2usr** [comment]
I just finished a build, plus the nightlies also went through just fine so must be something in your build environment.

**Comment by mpmckinney** [comment]
Ya, it's for sure not that commit above that I did a while back. I've built many times since that commit and I have another build that is finishing up as we speak, so like gs2usr said, it must be something on your end or specific to that device maybe.

**Comment by blindndumb** [comment]
Just checked the androidfw directory was not present, IDK how 
Fixed by 
rm -rf frameworks/base and then sync again
