### ISSUE TITLE
landscape reboots

### ISSUE THREAD

**Issue by atrus5** [PAC-ROM/android_vendor_pac#125]
Hello,

I don't know where to ask this exactly.  I don't know if this is specific to my phone or not.  I have the htc one s.  When in landscape mode, if the phone goes to sleep or is turned off the phone reboots.  I don't know if this is a common bug.  Just thought I would mention it.  Maybe it's already known if so then close this issue.

**Comment by Papa-Smurf151** [comment]
Take it to pac forum
