### ISSUE TITLE
Device tree - spring cleaning

### ISSUE THREAD

**Issue by szlkiev** [PAC-ROM/android_vendor_pac#131]
As you guys can see, our girhub account is flooded by many devices tree.
The problem are, many of them were just forked here but is 100% identical with cm's which is pointless or they are already abandoned or even worse isnt used anymore in these current pac project.

So we will do some clean up, for every maintainer who has device tree forked here but actually can use cm ones (still get supported by cm) please remove it and update your device.dependencies

For the rest, we will delete them if they aren't stated in any device.dependecies

Thats is for now, we'll do cleaning phase 2 later

Regards

**Comment by blindndumb** [comment]
And may be device maintainers should fork it to their own account.
EDIT : Sorry accidentally pressed close, Re Opened!!

**Comment by Nick0703** [comment]
I agree with blindndumb. If we do that, our github (PAC's) will look clean.

**Comment by szlkiev** [comment]
This is what singh_dd93 did weeks ago, and we're using it in our dependencies

https://github.com/pac-semc7x30

**Comment by Nick0703** [comment]
Ah I see! I'll probably make one for Samsung devices then.

**Comment by Papa-Smurf151** [comment]
Why not just make a pac-devices github and use it for all.  That way there
aren't a ton of different pac githubs

**Comment by Nick0703** [comment]
@szlkiev, is that ok with you? If we make one pac-devices github?

**Comment by singhdd93** [comment]
@Papa-Smurf151 I think different organisations should be made for different company devices
that will keep the organisation clean and easy to maintain

**Comment by Papa-Smurf151** [comment]
Either way is fine.  Just only fork what is needed.  If it's maintained by
cm or the muppets then no need for us to host it.  Just means more merging
and updating for no reason.

**Comment by singhdd93** [comment]
I had to fork all repos as there is no official CM support of CM10.1 for our devices and many times the device tree in originally maintained repos become unstable

**Comment by szlkiev** [comment]
Both ways looks good to me.

**Comment by szlkiev** [comment]
Down from 79 to 60
Will need more dependencies changes to reduce more of them.
In the meanwhile I just moved repo ownership to github.com/szlkiev for a temporary backup

Now we have
PAC-semc7x30
PAC-samsung

**Comment by blindndumb** [comment]
@forum moderators..  Please reset my password of forum , The reset password option doesn't work
Username : blindndumb
Need to push changes..
BTW.. making a new PAC-htc too.. or has anyone already made it..

**Comment by Nick0703** [comment]
@szlkiev You can delete all the samsung repos. We forked all of them to PAC-samsung.

**Comment by singhdd93** [comment]
I still see semc device repos. @szlkiev please remove them

**Comment by szlkiev** [comment]
@nick, some dependency in jellybean branch haven't been edited, need to edit them first before remove the repos : i927, quincyatt
Also some samsung devices in cm-10.1 branch

@singhdd
Do you mind replace pac-semc7x30 jellybean branch with ones from pac-man?
Also in pac-semc7x30 we don't need other branches except jellybean & cm-10.1.
And update jellybean dependencies.
Once its done i'll remove all semc device trees

**Comment by Nick0703** [comment]
@szlkiev ok I'll edit them also.

**Comment by Nick0703** [comment]
@szlkiev I think it should be good now.

**Comment by szlkiev** [comment]
Path of proprietary i927 & quincyatt are non standard.
Should be proprietary_vendor_samsung instead just proprietary_vendor_i927 or vendor_quincyatt
Then no need repository proprietary_vendor_i927 anymore in PAC-samsung, so need to edit their dependency again

**Comment by Nick0703** [comment]
I was going to make them use the proprietary_vendor_samsung but I notice
that there was a few changes between them. I was afraid that if I make them
use it, it might break the builds for them. I'll update/merge or do
something else tomorrow. I can't update them right now.

**Comment by szlkiev** [comment]
OK,
One more error in Samsung gio.dependencies
Incorrect target path for android_device_samsung_gio
I believe this device was not buildable before, drunk maintainer :)

Edit: its stated in both gio.dependencies & gio.adds,  still, drunk maintainer :)

Down to 46

@blindndumb , mind helping us with HTC pyramid ?

**Comment by sudwind** [comment]
I also need to get my password reseted from the forum. And get added to the PAC-Samsung, since I'm the maintainer of tass, a msm7x27 device, and I provided the sources for beni, I forked most of the needed repos from androidarmv6 (some changes were needed, like the editing for the not yet ready BlueZ support or the newer atheros wifi libs). I'm just busy but still maintaing my source built pac for tass :) (and sorry for writing this here)

**Comment by blindndumb** [comment]
Will create PAC-htc tonight, HTC maintainers please contact me "blindndumb@gmail.com"
@szlkiev  I dont see any dependencies of Pyramid, also the device tree has not been updated since Sep 19,2012
It is useless .. better delete it..

**Comment by singhdd93** [comment]
@szlkiev  I will copy the jellybean branch of semc devices from PAC-man to PAC-semc7x30 within a day or two and also change the dependencies.

**Comment by championswimmer** [comment]
Another thing is, if there are any vendor trees on PAC (which might have required forking from TheMuppets or wherever), create separate account for them.
Blobs attract attention of DMCA-takedown sort of things. Though bigger projects like CM can be easier targets, it's preferrable to keep hands clean of any potential problems.
Worst case scenario is PAC-man github may get suspended (all repos) which will be very unfortunate.

**Comment by blindndumb** [comment]
@szlkiev android_device_htc_pyramid was useless, Deleted!
Also htc_msm8660-common was used in only evita and jewel (maintained by jameig71), rest htc devices are using CyanogenMod's , Deleted!  - It was also not updated since Sep

PM Sent to maintainer to update dependencies
So HTC is now clean, I guess!

**Comment by szlkiev** [comment]
Please check jellybean branch, might still be used there

**Comment by blindndumb** [comment]
@szlkiev Never mind evita and jewel are 8960 device, Actually 8660-common was forked by the one who forked device_pyramid.. So its none of use. BTW I checked jellybean too before deleting

**Comment by szlkiev** [comment]
@blindndumb, Great, now just left semc & lge

**Comment by singhdd93** [comment]
semc done
remove all repos

**Comment by szlkiev** [comment]
done, clean from device tree
