### ISSUE TITLE
Apology

### ISSUE THREAD

**Issue by InsomniaROM** [PAC-ROM/android_vendor_pac#154]
i apologize for compiling and posting 4.4 build before you say it was ready.

When i compiled on the 5th of dec there was no notice in terminal telling me this forgive me i meant no disrespect!

**Comment by zyonee** [comment]
You may want to remove any links and uploaded files until we say it's ok. A mistake is a mistake, but please remove it for the meantime.

**Comment by InsomniaROM** [comment]
removed and closed sorry if i had known otherwise it would not have happened!
