### ISSUE TITLE
about ParanoidAndroid Overlays definded at vendor/pac/config/pac_common.mk

### ISSUE THREAD

**Issue by BambooIV** [PAC-ROM/android_vendor_pac#162]
Was ParanoidAndroid renamed to AOSPA?Row 91st of pac/config/pac_common.mk,the vendor/pa/overlay/common couldn't be found.Maybe we should bring pa/prebuilt/apk/ParanoidPreferences.apk back from https://github.com/AOSPA/android_vendor_pa/tree/kitkat/prebuilt/apk.

**Comment by BambooIV** [comment]
FOR WHAT

**Comment by pvyParts** [comment]
Because ParanoidPreferences.apk does not a Hybrid Engine Make

**Comment by BambooIV** [comment]
All right,I got this.Thank you for your replying.

2014-02-19 10:30 GMT+08:00 Tim Pohlad-Thomas notifications@github.com:
