### ISSUE TITLE
Please fix Mango Overlay

### ISSUE THREAD

**Issue by singhdd93** [PAC-ROM/android_vendor_pac#18]
target Java: xmp_toolkit (/home/dds/PAC-man_CM10.1/system/out/target/common/obj/JAVA_LIBRARIES/xmp_toolkit_intermediates/classes)
device/semc/mango/overlay/frameworks/base/core/res/res/values/config.xml:35: error: Resource at config_symKeyShowsImePicker appears in overlay but not in the base package; use <add-resource> to add.
make: **\* [/home/dds/PAC-man_CM10.1/system/out/target/common/obj/APPS/framework-res_intermediates/package-export.apk] Error 1

I have attached the error.

**Comment by szlkiev** [comment]
added you as team member, your access vendor/pac, & all repos which are semc related.

please fix it if you have time

**Comment by singhdd93** [comment]
thanks
i fixed the above error but got error after it compiled kernel. It was some modules error.
Gonna look into that
