### ISSUE TITLE
Repo access to Xperia Devs

### ISSUE THREAD

**Issue by singhdd93** [PAC-ROM/android_vendor_pac#19]
Sorry to disturb you again.
But the Xperia devs does not have access to android_device_mango and also android_vendor_pac and few other Xperia repos
Plz fix it. 
I passed the compiling error of overlay and kernel but now stuck at legacy camera

**Comment by szlkiev** [comment]
fixed access.

legacy camera duplicated values_iw/strings?

**Comment by singhdd93** [comment]
Yes the same error. 
I did not get time to fix it yet as there is no power from morning.
I know i just need to remove the duplicated strings in String.xml

**Comment by ExPeacer** [comment]
Just remove line 57 and 58 from that xml.

**Comment by singhdd93** [comment]
I got the final zip and ROM is working fine.
Just the bluetooth which i know needs a new stack
Thanks for help.

I pushed the changes for mango.
Will be updating for other MDPI devices soon

**Comment by Druboo666** [comment]
singhdd93 
how did you fix Legacy Camera error
my build breaks at:

make: **\* [/home/pac-man/build/pac4.2/out/target/common/obj/APPS/LegacyCamera_intermediates/src/R.stamp] Error 1
make: **\* Waiting for unfinished jobs....
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
help me please

**Comment by singhdd93** [comment]
i just removed the line 57 & 58 from strings.xml

**Comment by Druboo666** [comment]
where can i find this strings.xml

**Comment by ExPeacer** [comment]
Please, it's Cyanogenmod issue.... Ask it there. The original problem fixed, please don't open this issue again.
Thanks a lot!
