### ISSUE TITLE
com.android.phone FC

### ISSUE THREAD

**Issue by singhdd93** [PAC-ROM/android_vendor_pac#24]
I built the PAC 4.2.2 today but getting the FC of phone.
i tried using the logcat but didnt have too much time to look into the error.
link to log http://dds.vigaas.com/log.txt
i hope somebody can work on this. I will work on it when I am free

**Comment by szlkiev** [comment]
try reverting this
https://github.com/PAC-man/android_packages_apps_Phone/commit/436e19f107e42d7d5339eaf74a4a5563ecab6f5b

i don't have the time either
if it work, please push the revert commit

**Comment by singhdd93** [comment]
thanks for looking into this. I understand that everyone has his life. Will try and if it works i will push the revert commit

**Comment by OldDroid** [comment]
Currently its working fine on my Devices (Samsung Galaxy Gio + Samsung Galaxy Tab 7)
Closed ...

(btw, maybe you forgotten to include your ril into the specific folders! Contact me here:
http://www.facebook.com/profile.php?id=100001798231333)

**Comment by singhdd93** [comment]
can you please tell me where to check for ril ?

**Comment by OldDroid** [comment]
tel me what your device is ;-)

**Comment by singhdd93** [comment]
device is smultron

**Comment by singhdd93** [comment]
@Druboo666 are you having any FC of phone ?

**Comment by singhdd93** [comment]
Chuck it guys i fixed it
Was the problem due to overlay. I changed the overlay and its fine now
gonna push changes now
