### ISSUE TITLE
Unfortunately System ui stopped

### ISSUE THREAD

**Issue by Druboo666** [PAC-ROM/android_vendor_pac#25]
in Navigation bar when choose menu button from rom control i am getting "Unfortunately System ui stopped"
but when i change to recent button then it okay
any idea....

**Comment by szlkiev** [comment]
anybody else to confirm this?

**Comment by metaiiica** [comment]
A member has reported me the problem too.

**Comment by szlkiev** [comment]
yes true, only the recent button that can't be replaced by any other button, not just menu button, because pa hardcoded it to auto switch between recent button into clear button vice versa.
which is currently conflicted with aokp nav edit button, let me see how pa managed to made it right with cm navbar edit button, that i reverted it & replaced with aokp ones.

come one guys, time for you all to look into codes also, not just compile it

**Comment by OldDroid** [comment]
well, im going to debug it in the java shit

**Comment by szlkiev** [comment]
In NavigationBarView.java
Add this line at line 640 (its an exact line as line 639, means we'll have 2 identical lines at 639 & 640)

        getRecentsButton().setVisibility(disableRecent     ? View.INVISIBLE : View.VISIBLE);

Please test it, if it fix this issue, please commit it

**Comment by szlkiev** [comment]
Anyone test it?

**Comment by OldDroid** [comment]
will do tomorrow on my gtab ;-)

**Comment by metaiiica** [comment]
how find i this file?? Would test now

**Comment by szlkiev** [comment]
Use search ?

TOP URGENT
The all future commits will be unimportant if we dont fix it soon

**Comment by bluefa1con** [comment]
syncing and trying this fix
stay tuned
pac/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone
Edit:file is missing on our git ? i can see it on my driver but not on git

**Comment by OldDroid** [comment]
https://github.com/PAC-man/android_frameworks_base/blob/cm-10.1/packages/SystemUI/src/com/android/systemui/statusbar/NavigationBarView.java

**Comment by bluefa1con** [comment]
szl that fix doesnt work
the recent button doesnt change to clear all button now but system UI still forcecloses if you change the recent app button in rom control
how about removing the pa recent code? we already have a clear all button from aokp

**Comment by szlkiev** [comment]
Don't give up so soon. We all should dig deeper, we have many members here. If no one else care,  then replace all nav button codes to aokp

**Comment by bluefa1con** [comment]
33 members.... yet no one looked at it other than the usual 4-5 people come on guys dig deeper i am busy with enough things already

**Comment by mpmckinney** [comment]
I just tried it and it works fine for my device... d710

**Comment by mpmckinney** [comment]
This was on a build made on March 5 by the way

**Comment by szlkiev** [comment]
Using my additional line or without?

**Comment by singhdd93** [comment]
works fine for me too. with the current file. I have made no changes to any file locally

Edit 
It starts FC after trying to open recent apps.

**Comment by mpmckinney** [comment]
Edit: never mind, I now see the problem... :(

**Comment by szlkiev** [comment]
The issue is we get fc when we change/replace recent button with  other button.

My fixcode attempt is, make an exact duplicate line of line 639 & put it at 640, means we will have 2 exact same line at 639 & 640

**Comment by singhdd93** [comment]
gonna try it out man
line 649 is 
final boolean disableRecent = ((disabledFlags & View.STATUS_BAR_DISABLE_RECENT) != 0);

have to duplicate this line?

**Comment by bluefa1con** [comment]
fixed
https://github.com/PAC-man/android_frameworks_base/commit/c4ffe84727dbb758083e133ae95bdb5e92438f74
work around, the recent app icon doesnt change to clear all but in return it fixes this annoying bug
if you find a better way commit it
