### ISSUE TITLE
Wi-fi issue

### ISSUE THREAD

**Issue by Druboo666** [PAC-ROM/android_vendor_pac#27]
For WI-FI to work have restart after first boot

any one have this issue......??????

**Comment by OldDroid** [comment]
tell me your device pls! i dont have this issue on my both devices (gio & sgt7), it can be that is a device related error in your device config ;-)

**Comment by singhdd93** [comment]
ya had the same thing on Xperia Mini(smultron) and Xperia Mini Pro(mango)

@OldDroid - plz help me with that phone FC thing

**Comment by Druboo666** [comment]
My phone is Xperia NEO V (haida)

**Comment by OldDroid** [comment]
pls gimme a logcat for this issue

**Comment by bluefa1con** [comment]
works fine on i9100, i9100G and Nexus 4
logs would be nice

**Comment by metaiiica** [comment]
many user report me, Wifi not work correcty. When User flash a alternative Kernel, now work all fine (Device LG P990 with new Bootloader)

**Comment by Papa-Smurf151** [comment]
Your modules in the IMG are not correct. When they flash a different kernel
it replaces the modules as well. My suggestion is you find the correct
modules and commit them to ur build

**Comment by metaiiica** [comment]
i use only the kernel from cyanogenmod for lg p990 with the different patch for use with the new ics Bootloader. But we use the old GB Bootloader too, this is supported by CM only. its a confuse thing with our device so we use all the different Kernel. But this is not public.

**Comment by OldDroid** [comment]
DEVICE specific
