### ISSUE TITLE
Settings FC on adding tiles

### ISSUE THREAD

**Issue by singhdd93** [PAC-ROM/android_vendor_pac#37]
Anyone else having this issue.
Many users of my builds are reporting the same.

**Comment by Nick0703** [comment]
It's working fine for me?

I'm using a Samsung Galaxy S Captivate

**Comment by singhdd93** [comment]
device please
I am using on Xperia Mini & Xperia Mini Pro

Any other Xperia user please tell

**Comment by OldDroid** [comment]
every phone have this issue, im investigating

**Comment by singhdd93** [comment]
OK then its fine. I thought some problem in my builds.
