### ISSUE TITLE
Custom Releasetool is deprecated.

### ISSUE THREAD

**Issue by oerner** [PAC-ROM/android_vendor_pac#47]
don't know if somebody else gets that error but in build/core/Makefile tells it us
that Custom Releasetool is deprecated. The guys of CM got also rid of squisher:
https://github.com/CyanogenMod/android_vendor_cm/commit/c1a5cc781ccf71a14d91a902b1251d85cd88af3a

**Comment by metaiiica** [comment]
have this too... Can delete the Folder /vendor/cm/tools solve this problem?

**Comment by oerner** [comment]
just delete the line in config file

If nobody gots a problem with that I gonna do that but than there will be no optimazion on the final script I think.

**Comment by oerner** [comment]
to fix it you have to revert this in your local repo:
https://github.com/CyanogenMod/android_build/commit/b51dd7cc690e9d353aa784132e67b43d4e8a5a0f

**Comment by OldDroid** [comment]
does this break the build?

**Comment by TheRealChickenlegs** [comment]
My build last night stopped with this error, it produced a PAC_i9100-ota zip that is 160mb I haven't had a chance to see if it flashes correctly yet it looks ok everything is there in the zip. I would imagine the size difference is because squisher was removed as well.

**Comment by oerner** [comment]
for me it stopps without dropping a zip i think,
I've removed earlier the line Makefile that checks if
a cutom releasetool is setted up and then stops the build.
I got then a cm10.1 zip

**Comment by bluefa1con** [comment]
we need the squisher for PA
we will be forking out android_build now
https://github.com/PAC-man/android_build
