### ISSUE TITLE
PACman BuildBox (ALL DEVICE MAINTAINERS NEED TO REPLY)

### ISSUE THREAD

**Issue by bluefa1con** [PAC-ROM/android_vendor_pac#54]
hey guys
i have a great news for you guys. The guys at basketbuild are offering us buildbox and hosting for pacman.Now i need some help from you guys to have as many devices to build automatically as we can. The buildbox will build stable aswell as nightlies when needed.

To have your device on buildbox here are the conditions
1. Your dependencies and manifest files should be complete under
https://github.com/PAC-man/android_vendor_pac/tree/cm-10.1/manifest (only use the removes where needed)
https://github.com/PAC-man/android_vendor_pac/tree/cm-10.1/dependencies
1. The settings you pushed for your devices MUST be able to build pacman and the output zip must be working as you wont be able to add or remove stuff from zip, it will be automatically uploaded to the file host when built.
2. You must specifically tell me to include your device in the buildbox as i wont risk adding devices unless told my the device maintainer.
3. You must have the spirit of sharing and open source and not using pacman to get fame, for example useless themes and tweak apps. Things like these maybe included in a separate zip on your thread but they must not be associated with pacman.
4. There must be atleast a significant amount of people using your builds, for example a device that has under 100 downloads per release will take time off buildbox but wont be able to deliver to as much people as a semi popular device. So i will prefer devices having atleast a decent amount of activity related to pacman. In short we dont have infinite spots so i will prefer more popular devices over less popular.

Another thing i need some people to manage buildbox with me.
1. The buildbox access is a sensitive thing and comes with great power so i will only be accepting people who i or szl trust and have contributed to the project.
2. You must be able to configure and have knowledge of linux terminal via SSH. Ability to write build script etc will also be appreciated.

i also need some ideas about layout of the download page.
we will be getting a special pacman domain on the site basketbuild.com
i was thinking about 2 folders: Official Release and Nightlies, and they can be further divided to devices
or Device Folders and than Official Release and Nightlies inside
which one do you think is better? the first one is how CM manages it

NOTE: Dont close this, i will close it once i feel its time to

**Comment by blindndumb** [comment]
Cool man ! that's awesome..
I will update the dependencies , adds and removes soon for desire s.
Downloads are more than 5000 for RC's

Getting files ready to support Desire HD and Incredible S too

**Comment by cmartinbaughman** [comment]
I'm very interested in this one! I maintain 3 devices.  One is very popular (about 600 downloads to 800) but the others one has around 500 or so downloads per release and the other only about 250 give or take. Would only the more popular of the three be eligible for inclusion? 
Let me know if you need help with any setup or whatever, I was a developer for an ISP for a few years and have been using Linux as my OS for over a decade.

**Comment by jaydub82** [comment]
I would love this. As of now though the devices I maintain ( Hercules and
t0lte ) are a litle light on downloads. If they pick up I will let you know.

**Comment by mpmckinney** [comment]
You already know I'm in :)

Hit me up on gtalk, I have something to show you/talk to you about. I put a script together for all devices which includes test and release uploads and I could add in nightlies as well.

**Comment by oerner** [comment]
great!
the p920 gets about 250 downloads would be nice to have it in the buildbox cause my upload speeds are crap :D

**Comment by gs2usr** [comment]
skyrocket gets pretty decent downloads, everything's in place for it to build. it'd be greatly appreciated if it was included. I like the idea of the page like CMs with the exception of when you first arrive to the page, instead of showing all downloads, we should have the PAC logo and some quick info about PAC-man ROM, as well as flashing  warnings and what not.

**Comment by bluefa1con** [comment]
adding  .remove files can cluster the local manifest on buildbox 
i think its better that we only use dependencies files unless really needed to change a pacman/cm repo for a third party
i am testing the buildbox right now
page will be done tonight but we can edit it later

**Comment by metaiiica** [comment]
this is a good idea, but yesterday i have registered a new Domain for use with OTA-Updater so i can upload directly to the Domain... Have fast speed and the upload is fast too..in the Moment i would build a automatic uploader and automatic subscriber for the OTA. Must see if that work

**Comment by Druboo666** [comment]
Dont Forget About Haida (Xperia Neo V)
as this one is also quite popular

**Comment by Papa-Smurf151** [comment]
I'd like to add d2spr to build box. Ill make sure all the vendor files r up
to date when i get home from work

**Comment by gs2usr** [comment]
@bluefa1con, so does everyone need to update their pac_(product).mk files to include:
GET_DEPENDENCIES := $(shell vendor/pac/tools/getdependencies.py $(PRODUCT_NAME))
so that all dependencies get added to the buildbox' local minifest?

**Comment by mpmckinney** [comment]
@gs2usr, no, the build script we have does that already so the device files themselves don't need to be changed as long as there is a device.dependencies file

**Comment by gs2usr** [comment]
Thanks for the response.

**Comment by bluefa1con** [comment]
sniper saved me time in writing a new script
he made a script that will compile and upload the build to either nighly or stable folders

**Comment by jaydub82** [comment]
Bluefa1con,
Is there anything I need to do to get my devices ready for the build bot?
Sorry trying to follow but I am at work so its kinda hard.

**Comment by Nick0703** [comment]
Thanks! It would be nice to have a buildbox for my captivatemtd.

**Comment by bluefa1con** [comment]
@jaydub82 just make sure there is a dependencies file for your device

**Comment by singhdd93** [comment]
Nice thing but My devices dont need this at all. The max downloads is 100 of a nightly of Mango/Coconut and other two have even lesser

**Comment by jaydub82** [comment]
@bluefa1con thanks t0lte and Hercules are good to go.

**Comment by bluefa1con** [comment]
http://pacman.basketbuild.com/saga build up
please test and report back i will build the rest tonight

**Comment by blindndumb** [comment]
Tested SAGA , Working fine !! 
The clock issue still there , I will commit a fix tonight :)

**Comment by OldDroid** [comment]
add me ;-) will rebase my manifest aswell ;-)
oh and my roms gots over 26000+ downloads

**Comment by szlkiev** [comment]
Wow thats a lot, 26000 per every release, per device?
or globally for all of your several devices & summarize them from all release since beginning?

Xperia ray just get average 1500 downloads each release :-/

**Comment by OldDroid** [comment]
w8, for p500 i got around 3200 for the first release, on gio 6700 and on ace almost 10000 compared with the last statts :)

**Comment by bluefa1con** [comment]
some changes i need to tell you guys
if your device cant use the default CM/PACman repos i cant include that in the buildbox
it ruins the point of having automated builds when you have to change the local manifest every time for different devices
this includes changing the camera app, changing the proprietary vendor folder to a custom one having custom framework/native etc repos
so i need you guys to include ONLY THE DEVICE TREE IN THE DEPENDENCIES FILE
yesterday when i launched buildbox for a nightly build it failed because the local manifest had different repos removed and added from different devices
here is an example of what happened http://pastebin.com/ZHNUwsbZ

  <remove-project name="CyanogenMod/android_hardware_qcom_media" />
  <remove-project name="CyanogenMod/android_hardware_qcom_display" />
  <remove-project name="CyanogenMod/android_hardware_qcom_audio" />
  <remove-project name="CyanogenMod/android_hardware_libhardware" />
  <remove-project name="CyanogenMod/android_device_common" />
  <remove-project name="CyanogenMod/android_frameworks_native" />
  <remove-project name="CyanogenMod/android_frameworks_av" />
  <remove-project name="PAC-man/android_packages_apps_Gallery2" />
  <remove-project name="PAC-man/android_packages_apps_Camera" />

changing repos like this will ruin the buildbox so comply with the instructions and include only the device tree if u want automated builds

**Comment by blindndumb** [comment]
May be we can do this way..
It will check if roomservice.xml is present or not at start of build. If yes then it will delete it and continue with creating a new roomservice.xml for the device, fetching its repo and building !

The problem is devices are old and now they are no more compatible with hardware repos of CyanogenMod.

**Comment by inyourface09** [comment]
At about 6000 dl's for primoc and primou. Once i get the build stable ill add the adds and removes for them. I'm very happy about this Pacman is growing faster than I ever could have hoped.

**Comment by oerner** [comment]
crespo first builf got about 100 downloads in less then a day

**Comment by OldDroid** [comment]
agreed with blinddump, many xperia devices using aswell new hardware things, for my one (armv6 repos) there are around 17 trees to re-new so build doesnt land in trouble

**Comment by atrus5** [comment]
Would love to use this feature.  I don't add anything to the rom after building it with the exact same files as what is merged with the pac vendor.  I am at 250 downloads after 2 days.  I am new to maintaining this so I don't know yet what a full release will look like as far as numbers go.  They have taken down the blob files and device tree for the ville, some violation of terms.  I am using my own repo for that.  I hope this is acceptable.  I don't know how to use the adds and removes files yet.  If someone could help me understand how to use that I would appreciate it.  Thank you.  Would love to learn.

**Comment by klin1344** [comment]
Please add d2tmo, d2att, and d2vzw.  They build fine using the default CM / PAC-Man repos, with no need for adds and removes files.  They get around 500 to 600 downloads each, per each new build (every 3-5 days).  Thanks for this, and I think that users would really appreciate nightlies for PAC-Man.

**Comment by klin1344** [comment]
I have fixed up the dependencies for the all the d2's, so you can add them to the buildbox for future nightlies / releases.  Thanks.

**Comment by C457** [comment]
Wish the fascinate and epic 4g were more popular, but updated fascinate .adds and removes to fix force closing issue.

**Comment by Nick0703** [comment]
I updated the captivatemtd manifests, it should be compatible with the buildbox now.

**Comment by bluefa1con** [comment]
the devices that are confirmed to work and are on buildbox
i9100
i9100G
mako
grouper
maguro
d710

**Comment by gs2usr** [comment]
Are there any confirmed not working?

**Comment by bluefa1con** [comment]
any device which changes the default repos
the buildbox is getting an upgrade soon and i might add more devices

**Comment by klin1344** [comment]
Bluefa1con, can you try d2tmo, d2att, and d2vzw when you have time and the resources?  They do not change the default repos; all that is tracked in the local_manifest are the additional device trees and the kernel for those devices.
A d2tmo build I uploaded on 3/13 just hit over 1000 downloads, and the d2att and d2vzw have about 700 each.
Thank you.

**Comment by jaydub82** [comment]
Can you also run
t0lte
hercules

They only pull device trees and kernel to local_manifests as well

**Comment by OldDroid** [comment]
i think you should try a build with 1 of my armv6 devices to test it fully! they are replacinf in manifest around 20 repos ;-)

**Comment by szlkiev** [comment]
The repo in buldbox is static, because its used to build several devices at the same time, so the repo can not be switched to others than the main manifest, unless it been told to build 1 by 1 with repo syncing first every time before it build a different device, so if in 1 day the server build for 20 devices, mean it will repo sync 20 times.

So it depends on the build script for a batch build

**Comment by mpmckinney** [comment]
@bluefa1con and everyone else

The last one is finishing uploading, but I just ran a successful build of the following on the bot:
i9100, i9100G, mako, maguro, d710

And that was just with one command :)

bluefa1con, you wrote it down, but we don't currently have support for grouper?...

**Comment by vertigo2012** [comment]
I've just built grouper and was going to open a thread tomorrow, well today now lol... Squared it with bluefa1con, just been waiting for the right time to build... let me know if someone else wants to do it ;)

Glad the mako built ok with the PA kernel instead of CM

**Comment by mpmckinney** [comment]
@vertigo2012 You're welcome to submit a commit for the device if you want :)

**Comment by Nick0703** [comment]
@Sniper- Could you make a test build for the captivatemtd, p3100, p3110, p5100 and p5110? I updated their manifests and dependencies.

**Comment by mpmckinney** [comment]
Alright, so I just set up the bot to do nightlies of the following devices:

i9100, i9100G, mako, grouper, maguro, d710

@Nick0703 Do those add/remove from the default repos or just have local manifest edits?

**Comment by Nick0703** [comment]
@Sniper- Yeah those add/remove are from the default repos (captivatemtd) and for the p31xx and p51xx I had to use another repo sources as the CM's one don't work properly for the device. But either way both of them don't modify or change any of PAC's repos.

**Comment by klin1344** [comment]
Sniper, could you include d2tmo, d2att, and d2vzw (US Galaxy S3's) in the nightlies?  They do not add or remove the default repos and just use the local manifests for device trees and the kernel.  

Thanks.

**Comment by Papa-Smurf151** [comment]
and d2spr

**Comment by mpmckinney** [comment]
I added all the d2's

@Nick0703 they're building now.

**Comment by Nick0703** [comment]
@Sniper- Thanks!

**Comment by Papa-Smurf151** [comment]
Am i missing the website where the nightlies are.

**Comment by mpmckinney** [comment]
@Papa-Smurf151 once made they'll be at http://www.pacman.basketbuild.com/ under the device name and then the nightlies folder. The nightlies script hasn't run yet and is set to run at 1am PST/4am EST.

**Comment by Papa-Smurf151** [comment]
Ah seeing that now. Thanks

**Comment by klin1344** [comment]
@Sniper- Thanks a ton. :)

**Comment by Papa-Smurf151** [comment]
Something is wrong with d2spr build on build bot

Just built a fresh build and it works from just pulling directly off pac git
146.93mb

Then build bot us 138.5 mb

Fresh build flashes and reboots perfectly

Build bot flashes but wont boot. Samsung pops up for a min then screen goes
black and stays black

Any ideas. Maybe something in the build script

**Comment by mpmckinney** [comment]
I think it has to do with the local manifest. I had just made some changes to how the build works so I'll revert them and try again.

**Comment by Papa-Smurf151** [comment]
Sounds good. Does that mean no way to find out till tomorrow when it auto
builds again or can u run a test

**Comment by Grarak** [comment]
@Papa-Smurf151 I guess you forgot the vendor/samsung files

**Comment by Papa-Smurf151** [comment]
How is that possible if its building for me but not on bot

**Comment by mpmckinney** [comment]
I'll run a test in a little bit. Was it only the d2spr that's messed up?

**Comment by Papa-Smurf151** [comment]
Not sure as i don't maintain any of the others

**Comment by Nick0703** [comment]
@Sniper- The files for the build bot are located here right? http://www.pacman.basketbuild.com/ Because I've checked it and I still didn't see the files for my devices?

**Comment by mpmckinney** [comment]
@Nick0703 ya sorry, I ran into some errors with them but it could've been on my end so I'll try again when I get a chance.

**Comment by Nick0703** [comment]
@Sniper- It's fine man! Take your time lol! :)

**Comment by mpmckinney** [comment]
@Papa-Smurf151 I'm running the d2spr now so in a little while you can check to see if what I did fixed it. @Nick0703 don't worry, you're gonna be right after it ;)

**Comment by Papa-Smurf151** [comment]
@mark roger roger. You da man

**Comment by klin1344** [comment]
@Sniper- the other d2's are broken as well.  Hope you can get it fixed, thanks!

**Comment by Papa-Smurf151** [comment]
klin they are all fixed.  they will be built on the next build date.
 Problem was in the build script.  It different differentiate on the
roomservice.xml and all got messed up. Sniper has fixed the issues and ran
a test with the d2spr and I have a working build now.

**Comment by klin1344** [comment]
@Papa-Smurf151  Alright, thank you.

**Comment by metaiiica** [comment]
I find we should support all Devices was here officially integrated as nightly build... Why, we must other Devices give a Chance. We make P.A.C. Man bigger and and we become a positive Feedback. 
We may not look how often a Build per Device downloaded, we must all support. 

What do you think to this idea?

**Comment by bluefa1con** [comment]
@metaiiica not possible
old devices are not in cm jenkins for the same reason they have different repos that mess with the newer devices
plus if a device get 200 downloads per release, a nightly will be get about 50 downloads its not worth taking time off the buildbot that can serve more popular devices
we already have 6 hours from the buildbot everyday and other people have to use it too we cant take it for the whole day
one thing we can do for newer devices is fork out the vendor folders and add the missing parts but either way we can not support old arm6 devices

**Comment by OldDroid** [comment]
are you kidding me? -_-
my old pac got about 23000 downloads for sg ace and still no buildbox support? Oo

**Comment by Papa-Smurf151** [comment]
Buildbot has produced corrupt ROMs for past 3 builds. Any info you guys?
D2spr. One build has been suscessful and that was a forced build by sniper
on the buildbot

**Comment by KBizzle** [comment]
Ok. Most of you don't know me and probably a few do. I currently maintain the i605 and the l900. Not only that but I have been working with basketthis and using his build box since day 1. Matt has recently asked me to be a point of contact for you guys to answer questions about the bot and to assist sniper with any questions he may not be able to help with immediately. I am seeing that we are having an issue with builds for the d2 series of devices. I have kinda been taking a backseat on things but with the recent request from Matt and the fact that he was in a car accident yesterday, (he is Ok btw, just banged up) I'm going to try and find the time to dig in and resolve the issue. 

In the meantime, are there any other devices that are not building properly? 

Also, to all OG devs and contributors. Do you guys have an iirc set up? If not, I would like to do that, so we can get organized on the development end as well as the build box end. Please let me know so I can get on it ASAP. 

Once we can meet as a whole, we can start resolving some of these issues. 

Thanks guys,  
   Kyle
   Aka KBizzle

**Comment by IvanBrazza** [comment]
maguro wasn't building correctly either. There's an irc room, #pac-rom on freenode, but it's a ghost town lol

**Comment by KBizzle** [comment]
Thank you Ivan. We need to make it less of a ghost town. So, I know people live in different countries so I will try and be in the irc as much as possible, starting this evening. I'll be in there around 8 pm est. Please come join me and I'll work on getting these nightlies resolved. If it's too early/late for some, no biggie, ill stay logged in and you can pm me as we go.

**Comment by vertigo2012** [comment]
Mako isn't building correctly, I have let bluefa1con know also, I've built successfully and don't mind doing so until buildbot is fixed

**Comment by KBizzle** [comment]
Ok, thanks. I'm sure if we narrow down one, it will resolve the rest. So, I'll be on it this evening. Gotta do the fam thing for a little bit after work. I'm sure some of you can empathize. :-)

**Comment by bluefa1con** [comment]
this is why i want people to get involved in the forum different time zone forum is easy to track
about the corrupted build today i checked by pulling the build directly from the buildbot rather than from basketbuild download page and it was working fine so the issue is with basketbuild download site
@KBizzle thanks for coming here mate i talked to matt, move the conversation to the new updated issue that has devices that have been successfully added to the build bot or better yet move to the forum so its private

**Comment by szlkiev** [comment]
@olddroid, don't be jealous mate, my urushi & other 10 xperia 2011 devices that use the same device common tree and also need to replace many projects under PAC default manifest, still cant use buildbox, and i don't mind either

**Comment by bluefa1con** [comment]
@OldDroid it doesnt give me any pleasure or advantage to exclude devices from buildbot but you have to understand the limitations

**Comment by OldDroid** [comment]
well ok, i think i need to accept that ...

**Comment by shrike1978** [comment]
I'm currently getting between 250-400 downloads per release on vigor, though I don't think I'd come close to that on nightlies.  I don't know if that qualifies or not.  I'm currently working on the manifests a bit because CM is working on legacy device support, so I should be able to get rid of all the adds/removes soon and just have dependencies.  It is building completely correctly from the github as is, but I don't want to offer it up to the build box until I have the manifests totally settled with the CM changes.

Also, I signed up on the forum this morning, but I'm not seeing any posts.  Is there something extra I need to do?

**Comment by Papa-Smurf151** [comment]
Try it now. I have moved you to the maintainers group.

For all others who are not registered. Please register at forum and either
send me a pm

Papa Smurf151 on forum site or respond here with user name.

Please move all chat about pac man to forum for now on.

As soon as I'm given access to the server I will get tapatalk working to
make it easier.

**Comment by Papa-Smurf151** [comment]
Site for forum in cade people don't see it

http://pac-man-rom.de/dsfffddgdf/index.php

**Comment by tdm** [comment]
I'm a long time Linux hacker and ROM maintainer.  I'm interested in helping out with builds if you would like.

I have written a build daemon that is able to distribute builds among any number of servers to create an ad-hoc build farm.  The only requirements for servers to participate in a build farm are (1) reachable from the internet 24/7 (OpenVPN is acceptable if the machine is behind a NAT or some such), (2) reasonably fast internet connection, (3) running some reasonably recent version of Linux, (4) can build in less than an hour.  This could be used to coordinate nightly builds if we have a few folks who can contribute to the build farm.  I personally have 3 machines available: one clocks in about 20 minutes for a full build, the other two about 30 minutes.

How many devices do we have?  I'm counting 19 right now and I'll be adding iproj devices for 3 more.  I can probably do 22 builds in about 3 hours with just my boxes.

**Comment by Papa-Smurf151** [comment]
We have a build bot that is doing a number of builds in under 20 min each
already is this an alternative or add on to that

**Comment by tdm** [comment]
Whichever the team likes, or neither.  I'm flexible.  :)

**Comment by Papa-Smurf151** [comment]
Register on forum and I'll give u maintained access to talk about it there
http://pac-man-rom.de/dsfffddgdf/index.php

**Comment by bluefa1con** [comment]
@tdm please head over to forum maybe we can use your machine to build for legacy devices that we couldnt include with new devices

**Comment by Papa-Smurf151** [comment]
Hes already at forum and has a few threads over there already

**Comment by Papa-Smurf151** [comment]
FYI to all pac man maintainers...I have made a ton of changes to the site
last night. More to come.

The biggest change is ability to use tapatalk now.

Search for pac-man to find

**Comment by szlkiev** [comment]
Nice appearance & arrangement

**Comment by bluefa1con** [comment]
discussion moved to forums
