### ISSUE TITLE
Bootnanimation?

### ISSUE THREAD

**Issue by Nick0703** [PAC-ROM/android_vendor_pac#62]
Hey guys,

I was wondering when you compile a ROM, does the bootanimation.zip gets created or is the bootanimation already implemented in the framework? Because when my ROM.zip gets created, I get no bootanimation at all? Just a blank screen on start up.

**Comment by blindndumb** [comment]
There's no bootanimation.zip . The rom uses image from frameworks-res.apk's asset folder instead

**Comment by Nick0703** [comment]
But at least you get some sort of image on start-up right?

**Comment by blindndumb** [comment]
Yes !

**Comment by Nick0703** [comment]
Well, mine is a black screen? Nothing at all.....

**Comment by blindndumb** [comment]
Check your pac_#device.mk , Have you linked to any image ? Compare it with some other device pac.#devicemk

**Comment by Nick0703** [comment]
Here's mine? It's the same thing as pac_i9100.mk

# PAC device overlay

PRODUCT_PACKAGE_OVERLAYS += vendor/pac/overlay/pac/hdpi_480x800
$(shell cp -f vendor/pac/prebuilt/common/bootanimation_framework/android-logo-mask_samsung-hdpi.png frameworks/base/core/res/assets/images/android-logo-mask.png)

# PAC boot logo

PRODUCT_COPY_FILES += \
    vendor/pac/prebuilt/common/bootlogo/pac_logo_480x800.rle:root/logo.rle

**Comment by bluefa1con** [comment]
i am going to implement boot animations soon here is a preview http://i.picasion.com/pic66/f86b46df62f3a86d1123b3a46b5e5abc.gif all thanks to rwaempires

**Comment by Nick0703** [comment]
It looks awesome! Thanks!

**Comment by blindndumb** [comment]
That is an awesome bootanimation !

**Comment by szlkiev** [comment]
Cool, any other color option? I kind of bored with blue hollow color, in pac is loading i think is better using yellow pacman n yellow font color or something

Please inform the themer that lime green represent pa, pink is aokp's pink unicorn, blue is cm's cid. And pac is pacman's yellow.
So pour some yellow for our official color, what do you guys think?

**Comment by vertigo2012** [comment]
Someone put a nice bootanimation in Nexus 4 thread
![IMG00004](https://f.cloud.github.com/assets/1727884/253490/204614a4-8bd5-11e2-9744-a6703f919ecd.png)

original post here http://forum.xda-developers.com/showpost.php?p=38644026&postcount=213
