### ISSUE TITLE
[Q]Adding new remote 

### ISSUE THREAD

**Issue by blindndumb** [PAC-ROM/android_vendor_pac#63]
In local_manifest.xml / roomservice.xml , I use to add this to add a new remote 
remote name="cfx" fetch="https://bitbucket.org/codefirex/"

Problem is I am adding the projects/repositories of the remote in ".adds" , ".removes" . How to add the remote and fetch location?

**Comment by szlkiev** [comment]
What the local manifest data needs are:
Try this example, (i never use outside github actually , but hope it works)
Path : android/vendor/pac
Project name : codefirex/android_vendor_pac 
Remote name : https://bitbucket.org
Branch : cm-10.1

**Comment by blindndumb** [comment]
Solved by adding this .. https://github.com/PAC-man/android/commit/3efe2ca4a4ee8c842f4bd0ec91bf1f083e8257b2

and specifying project name = cfx
No need of account
