### ISSUE TITLE
Cherry picking and the author

### ISSUE THREAD

**Issue by bluefa1con** [PAC-ROM/android_vendor_pac#68]
hey
i have been seeing recently that you guys got a lot more active which is a great start. Its time to learn something new and improve on what you already know
when you guys cherry pick do it from the terminal, keep the original author's name and the commit name
dont push squashed commits, they make it harder to track issues and revert the actual commit that would be the reason for a issue.
keeping the original author name is VERY important, i dont want people pointing fingers at pacman for stealing/renaming commits.
cherry picking and keeping the original author was discussed in xda developer private chat and here are some example of what the developers had to say
"For both the GPL and Apache2 licenses, it's part of the agreement you made when you made your changes to contribute, then distributed said changes.

I can't say for some of the other parts in the external sources, as some might be BSD, MIT, X11, etc. Reading the license for your new iTunes update may be one of those things you just click accept on, but reading the license for software source code is usually a good idea 

XDA stands behind these license agreements and wants you to show credit where credit is due, because they also do not want to be liable for not fulfilling your agreement.

Showing the credit in git is by far the most efficient way to track credit. You could even automate generating the credits by wrapping a script around git log and filtering for cherry-picks, and extracting the original authors name, then sort -u the results."

"Yup. Usually when a commit is 90% someone else's code and I've made some changes to it beyond a simple cherry-pick, I preserve authorship as them and state in the commit message what I changed (and, if possible, link to the original source of the patch)."

You can use git commit --author="Name <email>" to keep authorship intact.
these are the words of some of the most respected devs in android community and we should learn from them

**Comment by klin1344** [comment]
I fully agree with you...it is very important to keep authorship intact when cherry-picking commits.  

Another way to do that is to use git commit -c sha1sumofcommit and the commit message and author will be kept intact.

**Comment by szlkiev** [comment]
This issue should remain open
