### ISSUE TITLE
get.pac

### ISSUE THREAD

**Issue by OldDroid** [PAC-ROM/android_vendor_pac#70]
so guys we will get a biiiiig website for listing our current stables, every month every device mentainer can roll out a STABLE which will be published there for every device we support ;-)

For now the website is mentained by our Designer PulseDroid and will have a colour sheme like the PAC Mans xD

and basically it will look like the get.cm ;-)

just a small example what he done:
http://www.thyme2serve.co.za/pulsedroid/

**Comment by oerner** [comment]
great!

**Comment by metaiiica** [comment]
makes it more confusing than it already is .... we have my site, then to another, and we have to be tinkered where the builds are built .... What is this?

make more sites!!!
