### ISSUE TITLE
Bootanimation

### ISSUE THREAD

**Issue by gs2usr** [PAC-ROM/android_vendor_pac#84]
Does everyone get new bootanimation included in the finished build zip? whenever i build i get this while the build is starting:

PRODUCT_COPY_FILES vendor/pac/prebuilt/xhdpi/bootanimation.zip:system/media/bootanimation.zip ignored.

and then i end up with CyanogenMods bootanimation in my finished zip.

**Comment by atrus5** [comment]
how did you get this to work?

**Comment by gs2usr** [comment]
had to edit /home/gs2usr/pacman/vendor/cm/config/common.mk && common_full_phone.mk and remove all the bootanimation references

**Comment by atrus5** [comment]
oh duh.  there it is.  thanks.

**Comment by szlkiev** [comment]
Like I said yesterday in someone else commit pull requests comment, you just need to move your Pac bootanim copy command before inherit cm.mk in pac_product.mk, that's all.

**Comment by atrus5** [comment]
Thank you.
