### ISSUE TITLE
Farewell

### ISSUE THREAD

**Issue by bluefa1con** [PAC-ROM/android_vendor_pac#88]
Alright folks it was a great time working with you guys
my exams are coming and i wont be active for the next 2 months
dont worry i will be back right after that
sniper will take care of buildbot 
i see you guys are already taking care of the repositories so i am not worried about that
take care and keep on the awesome work
pss someone should remove the bootanimations from vendor/cm
they overwrite the pac bootanimation
bluefa1con

**Comment by gs2usr** [comment]
Take your time my friend. Good luck on the exams 1

**Comment by TheRealChickenlegs** [comment]
Good luck mate I hope you smash your exams!! I has been great working with you and I look forward to your return.

Re the bootanimation the commits I made fix the issue Nick's fix worked perfectly so I have corrected all devices that already had the bootanimation in their device.mk. If anybody adds the new bootanimation just check a device.mk that has the fix commit and place the line for the zip in the same place and you will get the new PAC bootanimation.

**Comment by Wechy77** [comment]
Good luck on the exams. Waiting for your return.

**Comment by Nick0703** [comment]
Good luck on your exams! :)

**Comment by metaiiica** [comment]
Good luck on your exams!

**Comment by KBizzle** [comment]
Good luck on your exams.

**Comment by blindndumb** [comment]
Good luck

**Comment by szlkiev** [comment]
Bring back some A's will you, stay away from pacman github, too much pacman will give you many F's lol

**Comment by singhdd93** [comment]
All the best for your exams

**Comment by Druboo666** [comment]
all the best with ur exams

**Comment by bluefa1con** [comment]
haha @szlkiev yeah i am working for straight As
thanks guys

**Comment by OldDroid** [comment]
have vacations now ^^ and dont worry about pac, it will be in good hands ;-)
anyway, nick0703, me, blindndumb and gs2usr can handle it aswell ^^

**Comment by OldDroid** [comment]
oh i forgot metaiiica and xLaMbChOpSx

EDIT: If anyone of the devs wants to add smth new or have a problem with pac related to the framework, contact me on xda ;-)

**Comment by blindndumb** [comment]
Man , I am busy with my tests too and have to submit my last sem project before 20th of April which is yet in its initial stage. A lot of work to do in servlet and android. Basically its a Web-IDE with real time I/O and an android app for the same. Then I will be active in contribution. 
Till then all I can do is derp.

And one more thing I am getting a N4 soon , SO maybe I can handle PAC for that device too (Only If the current device maintainer doesn't has problem).

**Comment by cmartinbaughman** [comment]
I was wondering if you guys wanted to use this app I forked and have been making edits to locally, that I include in my builds, GooglePacman. If anyone remembers, for the anniversary of the Pacman video game from the 1980s, Google had a web-based version of it on their website that they released on their website, however it was done in Javascript. Well, this is the same thing, only implemented in Java by idukat. I merely have been making small changes to it and adding it to the rom from one of my device make files. It still needs resized more for my devices, but It's still quite playable, sorta-small and sort of a fun addition if anyone else wants to use it? Please let me know, it's over here if anyone wants to check it out: https://github.com/cmartinbaughman/google-pacman/

**Comment by szlkiev** [comment]
Kind of fun, lets try it :)

**Comment by cmartinbaughman** [comment]
Sorry just saw this. Should I add the source to the PAC-man repo or just add it from my repo to the manifest.xml?

**Comment by bluefa1con** [comment]
you would also need to add it in the android_build repo under common packages or it wont be compiled with rom
or you can define the package under each device

**Comment by mpmckinney** [comment]
Or you could add it to android_vendor_pac/config/pac_common.mk using:

PRODUCT_PACKAGES += \
    GooglePacman

**Comment by szlkiev** [comment]
If it already support multi DPI (at least mdpi hdpi & xhdpi), then as above said, pac_common.mk it is

**Comment by cmartinbaughman** [comment]
Cool thanks I'll put her in. Ill also add the code to the repo and it supports multiple dpi right now but I am still trying to get them perfect. Anyone that wants to update something for their device go for it!
