### ISSUE TITLE
No NavBar buttons in landscape when in Phablet UI

### ISSUE THREAD

**Issue by vertigo2012** [PAC-ROM/android_vendor_pac#91]
If you leave buttons as they are, they don't show up, if you add another button they show up but cut off and are a mirror image of normal buttons

**Comment by Nick0703** [comment]
Yeah, my uses are reporting the same problem also. And also is anyone else having some issues with the Browser? When you open it, it crashes back to the home screen?

**Comment by mpmckinney** [comment]
I can confirm this on a build I just compiled, and @Nick0703 my browser works fine.

**Comment by Nick0703** [comment]
@Sniper- Well this is weird? It doesn't work for me at all? Even on my phone it doesn't work lol? But it was working like 5 days ago and after that it stopped working. I'll delete my local browser repo and re-sync it to see if it works.

**Comment by bluefa1con** [comment]
the real problem here is nav bar issue
my device has hardware button so people didnt notice it but nexus 4 people have been reporting it and its a confirmed bug

**Comment by jeroenqui** [comment]
i can confirm that too, on the xperia z (yuga) (not officially supported yet, but i'm building it) on phablet mode the navigation bar doesn't show on landscape. 320 dpi / 600p (screen is 1920x1080)
I have looked into it, but I can't find the cause yet...

**Comment by Nick0703** [comment]
Did we commit something that's related to the Phablet UI? I'm looking at our commits and I can't find any? And @Sniper- Yep, my browser still doesn't work? It seems to be crashing when the page is loading?

**Comment by jeroenqui** [comment]
Is anyone able to look into this?

**Comment by gs2usr** [comment]
yes i believe ive got it fixed, im testing it now and will push a commit if its good.

**Comment by gs2usr** [comment]
Fixed
