### ISSUE TITLE
Buildbot and nightlies (update)

### ISSUE THREAD

**Issue by bluefa1con** [PAC-ROM/android_vendor_pac#94]
hey guys here are the list of devices that have been added to buildbot and should work fine
i9100, 
i9100G, 
mako, 
grouper, 
maguro,
tilapia,
d710,
d2spr,
d2tmo, 
d2att, 
d2vzw

these devices will be getting regular nightly builds and the folders can be found at http://pacman.basketbuild.com/
more over Sniper and Kbizzle are now managing buildbot
if your device can compile with the default cm repos without breaking build for other devices then comment below with your device code name and how many downloads your releases get and we may add more devices in the future.

**Comment by gs2usr** [comment]
Skyrocket gets very decent downloads I'd say about 500 per release, I weould be very great full if it was added,

**Comment by atrus5** [comment]
Would ville be ok to put on the nightlies?  I get about 750 per release.  I guess probably not because of a dmca takedown of two repositories. So I had to use two of my own repos.

**Comment by metaiiica** [comment]
You can add p990 also.

**Comment by bluefa1con** [comment]
move on to the discussion to forum here
http://pac-man-rom.de/forum/
if you are a maintainer of the devices listed above or if you wish to get your device added check the thread i just posted

**Comment by Papa-Smurf151** [comment]
Can I get approved for forum

Papa smurf151

**Comment by klin1344** [comment]
Me too, I can't log in with my username klin1344.  I requested a password reset and even with the new password I cannot log in.

**Comment by bluefa1con** [comment]
i cant find where to accept you guys the admin control panel isnt opening and the moderator settings didnt show anything wait for metaiica

**Comment by klin1344** [comment]
I can log in now, metaiica fixed it. :)

**Comment by Papa-Smurf151** [comment]
metalica i need you to hit me up on gtalk.  cbarlan@gmail.com

I need access to the server to add some plugins to the forum so that we can
have some new features and a style.

**Comment by bluefa1con** [comment]
moved to forum
