### ISSUE TITLE
Bottom bar is at top in recent calls list in portrait mode

### ISSUE THREAD

**Issue by jeroenqui** [PAC-ROM/android_vendor_pac#96]
When you open the recent calls list, the bottom bar (with the search icon, and the 3 dots) is placed at the top of the screen (as an overlay over the contact list)

This happens in portrait mode on phablet ui and might be related to the navbar not showing on landscape mode.

**Comment by jeroenqui** [comment]
the problem lies probably in one of the files in here:
packages/apps/Contacts/res/layout/

It probably has something to do with a paddingTop which has te be changed into paddingBottom as the bar should be at the bottom, and now is at the top.
It also looks like they've tried to fix this already in the "Frequently called" list in the phone application.
As you can see there, they've just shifted the whole list down, but the actionbar should still be at the bottom (there is now a gap at the bottom, where it should be placed)

**Comment by szlkiev** [comment]
No one help me update : phone, contacts, contacts provider, trebuchet in the last 2 months since my temporary leave

**Comment by ghost** [comment]
I am going to update phone, contacts, contacts provider, trebuchet as szlkiev is currently away

Phone : https://github.com/PAC-man/android_packages_apps_Phone/commit/a3ed6ba4acaa80da382b1bea56cea2c9d823b2c8
Contacts : Nothing Updated other than translations
^^ Provider : Nothing Much Updated or Nothing Updated
Trebuchet : https://github.com/PAC-man/android_packages_apps_Trebuchet/commit/168fb2480f75d7342b1a8a8dc1dce59405cfb15a

**Comment by szlkiev** [comment]
@Mithun46, great one

**Comment by ghost** [comment]
@szlkiev Can you add me in gtalk : mithuncursed4eva@gmail.com

**Comment by szlkiev** [comment]
Mithun, gtalk done added
