### ISSUE TITLE
Paranoid Preferences cut off in portrait

### ISSUE THREAD

**Issue by mpmckinney** [PAC-ROM/android_vendor_pac#98]
I'm not sure about you guys, but no matter the dpi and other settings (layout only has 360 available) but for my hdpi device (d710) PA prefs won't show up correctly in portrait mode. The screens are cut off even at the smallest dpi, but the rest of the screen can be seen if rotated into landscape mode... any ideas or people with this same problem?

![Screenshot_2013-04-09-14-00-40](https://f.cloud.github.com/assets/3046690/359245/5eecac42-a159-11e2-870f-1615bfcaedbf.png)

![Screenshot_2013-04-09-14-01-13](https://f.cloud.github.com/assets/3046690/359246/5eecdcda-a159-11e2-9cc3-56f1de6336da.png)

**Comment by Papa-Smurf151** [comment]
Start a thread in forum

http://pac-man-rom.de/dsfffddgdf/index.php

**Comment by Nick0703** [comment]
It's a known bug.  https://github.com/ParanoidAndroid/android_vendor_pa/commit/e99a9b192386ca186dfe5a52126ce6fbe7da79a5

**Comment by mpmckinney** [comment]
Oh ya, kinda forgot :P but now I see the known bug... thanks
